version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Next.js
      - "8000:8000"  # FastAPI
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOSTINGER_API_KEY=${HOSTINGER_API_KEY}
      # Otros valores de entorno necesarios
    restart: unless-stopped
