[build]
  command = "npm install && NEXT_TELEMETRY_DISABLED=1 npx --yes next build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --omit=optional"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# La siguiente redirección no es necesaria para Next.js ya que el plugin se encarga de eso
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  directory = "netlify/functions"
