[build]
  command = "npm install && NEXT_TELEMETRY_DISABLED=1 npx next build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps --omit=optional"
  NEXT_TELEMETRY_DISABLED = "1"
  IS_NETLIFY_DEPLOYMENT = "true"
  NEXT_PUBLIC_SITE_URL = "https://solarfluidity.shop"
  NETLIFY_USE_YARN = "false"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable_edge_functions = true
    experimental_trace = true

# Redirecciones adicionales para mejorar SEO y experiencia de usuario
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/python-api/*"
  to = "/.netlify/functions/python-api/:splat"
  status = 200

# Redirección para páginas no encontradas
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Redirección para preservar URLs antiguas
[[redirects]]
  from = "/categorias/*"
  to = "/categorias/:splat"
  status = 301

[functions]
  directory = "netlify/functions"
