[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
